### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by berot3** [MkDocsEditor/MkDocsEditor-Web#2]
This is for editing MkDocs-docs without needing to have a different editor installed locally? Nice! But what does it look like?

It would be interring to see it.

**Comment by markusressel** [comment]
Thx for your interest!
Yes this project aims to allow arbitrary markdown files. It requires the backend to run somewhere of course so there is minimal setup required.

Unfortunately this project (especially the web version) is still very much a work in progress and I have very little resources to continue to work on it. The android client is partly functional if you are interested in that.
I mean if you really want to have a look I can post a screenshot here :smile:

**Comment by markusressel** [comment]
I invested some time in finishing the Netlify integration so you can have a look at the current state here:
https://mkdocseditor.netlify.com/

Note though that without a backend server the File Browser will always be empty ;)

**Comment by berot3** [comment]
look really great! thanks!

I will give it a try with my mkdocs! 😄 

Sorry the stupid question but I dont understand why your editor is a mkdocs-editor and not a markdown-editor. what makes you editor a mkdocseditor?

**Comment by markusressel** [comment]
Have a look at the feature list described in the android repo: https://github.com/MkDocsEditor/MkDocsEditor-Android

Yes, this may not only work with MkDocs but thats what I personally use and what defines the structure of markdown files.
